/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.pojos;


import com.fasterxml.jackson.databind.JsonNode;

import java.io.Serializable;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthCredentials implements Serializable {

    private static final long serialVersionUID = -247034536;

    private UUID     _Id;
    private JsonNode jsonb;

    public AuthCredentials() {}

    public AuthCredentials(AuthCredentials value) {
        this._Id = value._Id;
        this.jsonb = value.jsonb;
    }

    public AuthCredentials(
        UUID     _Id,
        JsonNode jsonb
    ) {
        this._Id = _Id;
        this.jsonb = jsonb;
    }

    public UUID get_Id() {
        return this._Id;
    }

    public void set_Id(UUID _Id) {
        this._Id = _Id;
    }

    public JsonNode getJsonb() {
        return this.jsonb;
    }

    public void setJsonb(JsonNode jsonb) {
        this.jsonb = jsonb;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AuthCredentials (");

        sb.append(_Id);
        sb.append(", ").append(jsonb);

        sb.append(")");
        return sb.toString();
    }
}
