/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.pojos;


import com.fasterxml.jackson.databind.JsonNode;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLogOperation implements Serializable {

    private static final long serialVersionUID = -556510480;

    private UUID          id;
    private String        appCode;
    private String        appName;
    private String        moduleId;
    private String        userCode;
    private String        userName;
    private LocalDateTime optTime;
    private String        quoteAddr;
    private String        optMark;
    private JsonNode      jsonb;

    public TLogOperation() {}

    public TLogOperation(TLogOperation value) {
        this.id = value.id;
        this.appCode = value.appCode;
        this.appName = value.appName;
        this.moduleId = value.moduleId;
        this.userCode = value.userCode;
        this.userName = value.userName;
        this.optTime = value.optTime;
        this.quoteAddr = value.quoteAddr;
        this.optMark = value.optMark;
        this.jsonb = value.jsonb;
    }

    public TLogOperation(
        UUID          id,
        String        appCode,
        String        appName,
        String        moduleId,
        String        userCode,
        String        userName,
        LocalDateTime optTime,
        String        quoteAddr,
        String        optMark,
        JsonNode      jsonb
    ) {
        this.id = id;
        this.appCode = appCode;
        this.appName = appName;
        this.moduleId = moduleId;
        this.userCode = userCode;
        this.userName = userName;
        this.optTime = optTime;
        this.quoteAddr = quoteAddr;
        this.optMark = optMark;
        this.jsonb = jsonb;
    }

    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getAppCode() {
        return this.appCode;
    }

    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }

    public String getAppName() {
        return this.appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public String getModuleId() {
        return this.moduleId;
    }

    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }

    public String getUserCode() {
        return this.userCode;
    }

    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public LocalDateTime getOptTime() {
        return this.optTime;
    }

    public void setOptTime(LocalDateTime optTime) {
        this.optTime = optTime;
    }

    public String getQuoteAddr() {
        return this.quoteAddr;
    }

    public void setQuoteAddr(String quoteAddr) {
        this.quoteAddr = quoteAddr;
    }

    public String getOptMark() {
        return this.optMark;
    }

    public void setOptMark(String optMark) {
        this.optMark = optMark;
    }

    public JsonNode getJsonb() {
        return this.jsonb;
    }

    public void setJsonb(JsonNode jsonb) {
        this.jsonb = jsonb;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TLogOperation (");

        sb.append(id);
        sb.append(", ").append(appCode);
        sb.append(", ").append(appName);
        sb.append(", ").append(moduleId);
        sb.append(", ").append(userCode);
        sb.append(", ").append(userName);
        sb.append(", ").append(optTime);
        sb.append(", ").append(quoteAddr);
        sb.append(", ").append(optMark);
        sb.append(", ").append(jsonb);

        sb.append(")");
        return sb.toString();
    }
}
