/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.pojos;


import com.fasterxml.jackson.databind.JsonNode;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TMyLogin implements Serializable {

    private static final long serialVersionUID = -1742469891;

    private UUID          id;
    private String        userCode;
    private String        userName;
    private String        loginType;
    private LocalDateTime loginTime;
    private String        loginIp;
    private JsonNode      jsonb;

    public TMyLogin() {}

    public TMyLogin(TMyLogin value) {
        this.id = value.id;
        this.userCode = value.userCode;
        this.userName = value.userName;
        this.loginType = value.loginType;
        this.loginTime = value.loginTime;
        this.loginIp = value.loginIp;
        this.jsonb = value.jsonb;
    }

    public TMyLogin(
        UUID          id,
        String        userCode,
        String        userName,
        String        loginType,
        LocalDateTime loginTime,
        String        loginIp,
        JsonNode      jsonb
    ) {
        this.id = id;
        this.userCode = userCode;
        this.userName = userName;
        this.loginType = loginType;
        this.loginTime = loginTime;
        this.loginIp = loginIp;
        this.jsonb = jsonb;
    }

    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getUserCode() {
        return this.userCode;
    }

    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getLoginType() {
        return this.loginType;
    }

    public void setLoginType(String loginType) {
        this.loginType = loginType;
    }

    public LocalDateTime getLoginTime() {
        return this.loginTime;
    }

    public void setLoginTime(LocalDateTime loginTime) {
        this.loginTime = loginTime;
    }

    public String getLoginIp() {
        return this.loginIp;
    }

    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    public JsonNode getJsonb() {
        return this.jsonb;
    }

    public void setJsonb(JsonNode jsonb) {
        this.jsonb = jsonb;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TMyLogin (");

        sb.append(id);
        sb.append(", ").append(userCode);
        sb.append(", ").append(userName);
        sb.append(", ").append(loginType);
        sb.append(", ").append(loginTime);
        sb.append(", ").append(loginIp);
        sb.append(", ").append(jsonb);

        sb.append(")");
        return sb.toString();
    }
}
