/*
 * This file is generated by jOOQ.
*/
package com.generator.tables;


import com.bdhanbang.base.jooq.PostgresJsonBinding;
import com.fasterxml.jackson.databind.JsonNode;
import com.generator.Indexes;
import com.generator.Keys;
import com.generator.Tat0003ModLogin;
import com.generator.tables.records.TMyDataRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TMyData extends TableImpl<TMyDataRecord> {

    private static final long serialVersionUID = -324581628;

    /**
     * The reference instance of <code>tat0003_mod_login.t_my_data</code>
     */
    public static final TMyData T_MY_DATA = new TMyData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TMyDataRecord> getRecordType() {
        return TMyDataRecord.class;
    }

    /**
     * The column <code>tat0003_mod_login.t_my_data.id</code>.
     */
    public final TableField<TMyDataRecord, UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>tat0003_mod_login.t_my_data.data_type</code>.
     */
    public final TableField<TMyDataRecord, String> DATA_TYPE = createField("data_type", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>tat0003_mod_login.t_my_data.jsonb</code>.
     */
    public final TableField<TMyDataRecord, JsonNode> JSONB = createField("jsonb", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "", new PostgresJsonBinding());

    /**
     * Create a <code>tat0003_mod_login.t_my_data</code> table reference
     */
    public TMyData() {
        this(DSL.name("t_my_data"), null);
    }

    /**
     * Create an aliased <code>tat0003_mod_login.t_my_data</code> table reference
     */
    public TMyData(String alias) {
        this(DSL.name(alias), T_MY_DATA);
    }

    /**
     * Create an aliased <code>tat0003_mod_login.t_my_data</code> table reference
     */
    public TMyData(Name alias) {
        this(alias, T_MY_DATA);
    }

    private TMyData(Name alias, Table<TMyDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private TMyData(Name alias, Table<TMyDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tat0003ModLogin.TAT0003_MOD_LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_MY_DATA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TMyDataRecord> getPrimaryKey() {
        return Keys.T_MY_DATA_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TMyDataRecord>> getKeys() {
        return Arrays.<UniqueKey<TMyDataRecord>>asList(Keys.T_MY_DATA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMyData as(String alias) {
        return new TMyData(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMyData as(Name alias) {
        return new TMyData(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TMyData rename(String name) {
        return new TMyData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TMyData rename(Name name) {
        return new TMyData(name, null);
    }
}
