/*
 * This file is generated by jOOQ.
*/
package com.generator.tables;


import com.bdhanbang.base.jooq.PostgresJsonBinding;
import com.fasterxml.jackson.databind.JsonNode;
import com.generator.Indexes;
import com.generator.Keys;
import com.generator.Tat0003ModLogin;
import com.generator.tables.records.TWeXinOkapiRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TWeXinOkapi extends TableImpl<TWeXinOkapiRecord> {

    private static final long serialVersionUID = 37909257;

    /**
     * The reference instance of <code>tat0003_mod_login.t_we_xin_okapi</code>
     */
    public static final TWeXinOkapi T_WE_XIN_OKAPI = new TWeXinOkapi();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TWeXinOkapiRecord> getRecordType() {
        return TWeXinOkapiRecord.class;
    }

    /**
     * The column <code>tat0003_mod_login.t_we_xin_okapi.id</code>.
     */
    public final TableField<TWeXinOkapiRecord, UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>tat0003_mod_login.t_we_xin_okapi.tanent_id</code>.
     */
    public final TableField<TWeXinOkapiRecord, String> TANENT_ID = createField("tanent_id", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>tat0003_mod_login.t_we_xin_okapi.app_id</code>.
     */
    public final TableField<TWeXinOkapiRecord, String> APP_ID = createField("app_id", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>tat0003_mod_login.t_we_xin_okapi.app_secret</code>.
     */
    public final TableField<TWeXinOkapiRecord, String> APP_SECRET = createField("app_secret", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>tat0003_mod_login.t_we_xin_okapi.user_name</code>.
     */
    public final TableField<TWeXinOkapiRecord, String> USER_NAME = createField("user_name", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>tat0003_mod_login.t_we_xin_okapi.password</code>.
     */
    public final TableField<TWeXinOkapiRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>tat0003_mod_login.t_we_xin_okapi.note</code>.
     */
    public final TableField<TWeXinOkapiRecord, String> NOTE = createField("note", org.jooq.impl.SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>tat0003_mod_login.t_we_xin_okapi.jsonb</code>.
     */
    public final TableField<TWeXinOkapiRecord, JsonNode> JSONB = createField("jsonb", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "", new PostgresJsonBinding());

    /**
     * Create a <code>tat0003_mod_login.t_we_xin_okapi</code> table reference
     */
    public TWeXinOkapi() {
        this(DSL.name("t_we_xin_okapi"), null);
    }

    /**
     * Create an aliased <code>tat0003_mod_login.t_we_xin_okapi</code> table reference
     */
    public TWeXinOkapi(String alias) {
        this(DSL.name(alias), T_WE_XIN_OKAPI);
    }

    /**
     * Create an aliased <code>tat0003_mod_login.t_we_xin_okapi</code> table reference
     */
    public TWeXinOkapi(Name alias) {
        this(alias, T_WE_XIN_OKAPI);
    }

    private TWeXinOkapi(Name alias, Table<TWeXinOkapiRecord> aliased) {
        this(alias, aliased, null);
    }

    private TWeXinOkapi(Name alias, Table<TWeXinOkapiRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tat0003ModLogin.TAT0003_MOD_LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_WE_XIN_OKAPI_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TWeXinOkapiRecord> getPrimaryKey() {
        return Keys.T_WE_XIN_OKAPI_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TWeXinOkapiRecord>> getKeys() {
        return Arrays.<UniqueKey<TWeXinOkapiRecord>>asList(Keys.T_WE_XIN_OKAPI_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinOkapi as(String alias) {
        return new TWeXinOkapi(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinOkapi as(Name alias) {
        return new TWeXinOkapi(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TWeXinOkapi rename(String name) {
        return new TWeXinOkapi(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TWeXinOkapi rename(Name name) {
        return new TWeXinOkapi(name, null);
    }
}
