/*
 * This file is generated by jOOQ.
*/
package com.bdhanbang.weixin.entity;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.Generated;
import javax.validation.Valid;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.10.5" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLogLogin implements Serializable {

	private static final long serialVersionUID = -752127125;

	private UUID id;
	private String userCode;
	private String userName;
	private Short loginType;
	private LocalDateTime loginTime;
	private String loginIp;
	
	@Valid
	private IEntity jsonb;

	public TLogLogin() {
	}

	public TLogLogin(TLogLogin value) {
		this.id = value.id;
		this.userCode = value.userCode;
		this.userName = value.userName;
		this.loginType = value.loginType;
		this.loginTime = value.loginTime;
		this.loginIp = value.loginIp;
		this.jsonb = value.jsonb;
	}

	public TLogLogin(UUID id, String userCode, String userName, Short loginType, LocalDateTime loginTime,
			String loginIp, IEntity jsonb) {
		this.id = id;
		this.userCode = userCode;
		this.userName = userName;
		this.loginType = loginType;
		this.loginTime = loginTime;
		this.loginIp = loginIp;
		this.jsonb = jsonb;
	}

	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Short getLoginType() {
		return this.loginType;
	}

	public void setLoginType(Short loginType) {
		this.loginType = loginType;
	}

	public LocalDateTime getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(LocalDateTime loginTime) {
		this.loginTime = loginTime;
	}

	public String getLoginIp() {
		return this.loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	public Object getJsonb() {
		return this.jsonb;
	}

	public void setJsonb(IEntity jsonb) {
		this.jsonb = jsonb;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("TLogLogin (");

		sb.append(id);
		sb.append(", ").append(userCode);
		sb.append(", ").append(userName);
		sb.append(", ").append(loginType);
		sb.append(", ").append(loginTime);
		sb.append(", ").append(loginIp);
		sb.append(", ").append(jsonb);

		sb.append(")");
		return sb.toString();
	}
}
