/*
 * This file is generated by jOOQ.
*/
package com.generator;


import com.generator.tables.TLogLogin;
import com.generator.tables.TLogOperation;
import com.generator.tables.TLoginType;
import com.generator.tables.TMyLogin;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>userlib</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index LOG_LOGIN_PKEY = Indexes0.LOG_LOGIN_PKEY;
    public static final Index IDX_APP_CODE = Indexes0.IDX_APP_CODE;
    public static final Index IDX_APP_NAME = Indexes0.IDX_APP_NAME;
    public static final Index IDX_MODULE_ID = Indexes0.IDX_MODULE_ID;
    public static final Index IDX_OPT_MARK = Indexes0.IDX_OPT_MARK;
    public static final Index IDX_OPT_TIME = Indexes0.IDX_OPT_TIME;
    public static final Index IDX_QUOTE_ADDR = Indexes0.IDX_QUOTE_ADDR;
    public static final Index IDX_USER_CODE = Indexes0.IDX_USER_CODE;
    public static final Index IDX_USER_NAME = Indexes0.IDX_USER_NAME;
    public static final Index LOG_OPERATION_PKEY = Indexes0.LOG_OPERATION_PKEY;
    public static final Index T_LOGIN_TYPE_PKEY = Indexes0.T_LOGIN_TYPE_PKEY;
    public static final Index MY_LOGIN_PKEY = Indexes0.MY_LOGIN_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index LOG_LOGIN_PKEY = Internal.createIndex("log_login_pkey", TLogLogin.T_LOG_LOGIN, new OrderField[] { TLogLogin.T_LOG_LOGIN.ID }, true);
        public static Index IDX_APP_CODE = Internal.createIndex("idx_app_code", TLogOperation.T_LOG_OPERATION, new OrderField[] { TLogOperation.T_LOG_OPERATION.APP_CODE }, false);
        public static Index IDX_APP_NAME = Internal.createIndex("idx_app_name", TLogOperation.T_LOG_OPERATION, new OrderField[] { TLogOperation.T_LOG_OPERATION.APP_NAME }, false);
        public static Index IDX_MODULE_ID = Internal.createIndex("idx_module_id", TLogOperation.T_LOG_OPERATION, new OrderField[] { TLogOperation.T_LOG_OPERATION.MODULE_ID }, false);
        public static Index IDX_OPT_MARK = Internal.createIndex("idx_opt_mark", TLogOperation.T_LOG_OPERATION, new OrderField[] { TLogOperation.T_LOG_OPERATION.OPT_MARK }, false);
        public static Index IDX_OPT_TIME = Internal.createIndex("idx_opt_time", TLogOperation.T_LOG_OPERATION, new OrderField[] { TLogOperation.T_LOG_OPERATION.OPT_TIME }, false);
        public static Index IDX_QUOTE_ADDR = Internal.createIndex("idx_quote_addr", TLogOperation.T_LOG_OPERATION, new OrderField[] { TLogOperation.T_LOG_OPERATION.QUOTE_ADDR }, false);
        public static Index IDX_USER_CODE = Internal.createIndex("idx_user_code", TLogOperation.T_LOG_OPERATION, new OrderField[] { TLogOperation.T_LOG_OPERATION.USER_CODE }, false);
        public static Index IDX_USER_NAME = Internal.createIndex("idx_user_name", TLogOperation.T_LOG_OPERATION, new OrderField[] { TLogOperation.T_LOG_OPERATION.USER_NAME }, false);
        public static Index LOG_OPERATION_PKEY = Internal.createIndex("log_operation_pkey", TLogOperation.T_LOG_OPERATION, new OrderField[] { TLogOperation.T_LOG_OPERATION.ID }, true);
        public static Index T_LOGIN_TYPE_PKEY = Internal.createIndex("t_login_type_pkey", TLoginType.T_LOGIN_TYPE, new OrderField[] { TLoginType.T_LOGIN_TYPE.ID }, true);
        public static Index MY_LOGIN_PKEY = Internal.createIndex("my_login_pkey", TMyLogin.T_MY_LOGIN, new OrderField[] { TMyLogin.T_MY_LOGIN.ID }, true);
    }
}
