/*
 * This file is generated by jOOQ.
*/
package com.generator;


import com.generator.tables.TLogLogin;
import com.generator.tables.TLogOperation;
import com.generator.tables.TLoginType;
import com.generator.tables.TMyLogin;
import com.generator.tables.records.TLogLoginRecord;
import com.generator.tables.records.TLogOperationRecord;
import com.generator.tables.records.TLoginTypeRecord;
import com.generator.tables.records.TMyLoginRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>userlib</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TLogLoginRecord> LOG_LOGIN_PKEY = UniqueKeys0.LOG_LOGIN_PKEY;
    public static final UniqueKey<TLogOperationRecord> LOG_OPERATION_PKEY = UniqueKeys0.LOG_OPERATION_PKEY;
    public static final UniqueKey<TLoginTypeRecord> T_LOGIN_TYPE_PKEY = UniqueKeys0.T_LOGIN_TYPE_PKEY;
    public static final UniqueKey<TMyLoginRecord> MY_LOGIN_PKEY = UniqueKeys0.MY_LOGIN_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<TLogLoginRecord> LOG_LOGIN_PKEY = Internal.createUniqueKey(TLogLogin.T_LOG_LOGIN, "log_login_pkey", TLogLogin.T_LOG_LOGIN.ID);
        public static final UniqueKey<TLogOperationRecord> LOG_OPERATION_PKEY = Internal.createUniqueKey(TLogOperation.T_LOG_OPERATION, "log_operation_pkey", TLogOperation.T_LOG_OPERATION.ID);
        public static final UniqueKey<TLoginTypeRecord> T_LOGIN_TYPE_PKEY = Internal.createUniqueKey(TLoginType.T_LOGIN_TYPE, "t_login_type_pkey", TLoginType.T_LOGIN_TYPE.ID);
        public static final UniqueKey<TMyLoginRecord> MY_LOGIN_PKEY = Internal.createUniqueKey(TMyLogin.T_MY_LOGIN, "my_login_pkey", TMyLogin.T_MY_LOGIN.ID);
    }
}
