/*
 * This file is generated by jOOQ.
*/
package com.generator;


import com.generator.tables.AuthCredentials;
import com.generator.tables.Friend;
import com.generator.tables.FriendMessage;
import com.generator.tables.TMyData;
import com.generator.tables.TMyLogin;
import com.generator.tables.TWeXinOkapi;
import com.generator.tables.TWeXinUserinfo;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in tat0004_mod_login
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>tat0004_mod_login.auth_credentials</code>.
     */
    public static final AuthCredentials AUTH_CREDENTIALS = com.generator.tables.AuthCredentials.AUTH_CREDENTIALS;

    /**
     * The table <code>tat0004_mod_login.friend</code>.
     */
    public static final Friend FRIEND = com.generator.tables.Friend.FRIEND;

    /**
     * The table <code>tat0004_mod_login.friend_message</code>.
     */
    public static final FriendMessage FRIEND_MESSAGE = com.generator.tables.FriendMessage.FRIEND_MESSAGE;

    /**
     * The table <code>tat0004_mod_login.t_my_data</code>.
     */
    public static final TMyData T_MY_DATA = com.generator.tables.TMyData.T_MY_DATA;

    /**
     * The table <code>tat0004_mod_login.t_my_login</code>.
     */
    public static final TMyLogin T_MY_LOGIN = com.generator.tables.TMyLogin.T_MY_LOGIN;

    /**
     * The table <code>tat0004_mod_login.t_we_xin_okapi</code>.
     */
    public static final TWeXinOkapi T_WE_XIN_OKAPI = com.generator.tables.TWeXinOkapi.T_WE_XIN_OKAPI;

    /**
     * The table <code>tat0004_mod_login.t_we_xin_userinfo</code>.
     */
    public static final TWeXinUserinfo T_WE_XIN_USERINFO = com.generator.tables.TWeXinUserinfo.T_WE_XIN_USERINFO;
}
