/*
 * This file is generated by jOOQ.
*/
package com.generator;


import com.generator.tables.TLogLogin;
import com.generator.tables.TLogOperation;
import com.generator.tables.TLoginType;
import com.generator.tables.TMyLogin;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in userlib
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>userlib.t_log_login</code>.
     */
    public static final TLogLogin T_LOG_LOGIN = com.generator.tables.TLogLogin.T_LOG_LOGIN;

    /**
     * The table <code>userlib.t_log_operation</code>.
     */
    public static final TLogOperation T_LOG_OPERATION = com.generator.tables.TLogOperation.T_LOG_OPERATION;

    /**
     * The table <code>userlib.t_login_type</code>.
     */
    public static final TLoginType T_LOGIN_TYPE = com.generator.tables.TLoginType.T_LOGIN_TYPE;

    /**
     * The table <code>userlib.t_my_login</code>.
     */
    public static final TMyLogin T_MY_LOGIN = com.generator.tables.TMyLogin.T_MY_LOGIN;
}
