/*
 * This file is generated by jOOQ.
*/
package com.generator;


import com.generator.tables.TMyLogin;
import com.generator.tables.TWeXinOkapi;
import com.generator.tables.TWeXinUserinfo;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in tat0003_mod_login
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>tat0003_mod_login.t_my_login</code>.
     */
    public static final TMyLogin T_MY_LOGIN = com.generator.tables.TMyLogin.T_MY_LOGIN;

    /**
     * The table <code>tat0003_mod_login.t_we_xin_okapi</code>.
     */
    public static final TWeXinOkapi T_WE_XIN_OKAPI = com.generator.tables.TWeXinOkapi.T_WE_XIN_OKAPI;

    /**
     * The table <code>tat0003_mod_login.t_we_xin_userinfo</code>.
     */
    public static final TWeXinUserinfo T_WE_XIN_USERINFO = com.generator.tables.TWeXinUserinfo.T_WE_XIN_USERINFO;
}
