/*
 * This file is generated by jOOQ.
*/
package com.generator;


import com.generator.tables.AuthCredentials;
import com.generator.tables.TMyData;
import com.generator.tables.TMyLogin;
import com.generator.tables.TWeXinOkapi;
import com.generator.tables.TWeXinUserinfo;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tat0003ModLogin extends SchemaImpl {

    private static final long serialVersionUID = -1886699969;

    /**
     * The reference instance of <code>tat0003_mod_login</code>
     */
    public static final Tat0003ModLogin TAT0003_MOD_LOGIN = new Tat0003ModLogin();

    /**
     * The table <code>tat0003_mod_login.auth_credentials</code>.
     */
    public final AuthCredentials AUTH_CREDENTIALS = com.generator.tables.AuthCredentials.AUTH_CREDENTIALS;

    /**
     * The table <code>tat0003_mod_login.t_my_data</code>.
     */
    public final TMyData T_MY_DATA = com.generator.tables.TMyData.T_MY_DATA;

    /**
     * The table <code>tat0003_mod_login.t_my_login</code>.
     */
    public final TMyLogin T_MY_LOGIN = com.generator.tables.TMyLogin.T_MY_LOGIN;

    /**
     * The table <code>tat0003_mod_login.t_we_xin_okapi</code>.
     */
    public final TWeXinOkapi T_WE_XIN_OKAPI = com.generator.tables.TWeXinOkapi.T_WE_XIN_OKAPI;

    /**
     * The table <code>tat0003_mod_login.t_we_xin_userinfo</code>.
     */
    public final TWeXinUserinfo T_WE_XIN_USERINFO = com.generator.tables.TWeXinUserinfo.T_WE_XIN_USERINFO;

    /**
     * No further instances allowed
     */
    private Tat0003ModLogin() {
        super("tat0003_mod_login", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AuthCredentials.AUTH_CREDENTIALS,
            TMyData.T_MY_DATA,
            TMyLogin.T_MY_LOGIN,
            TWeXinOkapi.T_WE_XIN_OKAPI,
            TWeXinUserinfo.T_WE_XIN_USERINFO);
    }
}
