/*
 * This file is generated by jOOQ.
*/
package com.generator;


import com.generator.tables.TLogLogin;
import com.generator.tables.TLogOperation;
import com.generator.tables.TLoginType;
import com.generator.tables.TMyLogin;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userlib extends SchemaImpl {

    private static final long serialVersionUID = -480774474;

    /**
     * The reference instance of <code>userlib</code>
     */
    public static final Userlib USERLIB = new Userlib();

    /**
     * The table <code>userlib.t_log_login</code>.
     */
    public final TLogLogin T_LOG_LOGIN = com.generator.tables.TLogLogin.T_LOG_LOGIN;

    /**
     * The table <code>userlib.t_log_operation</code>.
     */
    public final TLogOperation T_LOG_OPERATION = com.generator.tables.TLogOperation.T_LOG_OPERATION;

    /**
     * The table <code>userlib.t_login_type</code>.
     */
    public final TLoginType T_LOGIN_TYPE = com.generator.tables.TLoginType.T_LOGIN_TYPE;

    /**
     * The table <code>userlib.t_my_login</code>.
     */
    public final TMyLogin T_MY_LOGIN = com.generator.tables.TMyLogin.T_MY_LOGIN;

    /**
     * No further instances allowed
     */
    private Userlib() {
        super("userlib", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TLogLogin.T_LOG_LOGIN,
            TLogOperation.T_LOG_OPERATION,
            TLoginType.T_LOGIN_TYPE,
            TMyLogin.T_MY_LOGIN);
    }
}
