/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.records;


import com.fasterxml.jackson.databind.JsonNode;
import com.generator.tables.AuthCredentials;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthCredentialsRecord extends UpdatableRecordImpl<AuthCredentialsRecord> implements Record2<UUID, JsonNode> {

    private static final long serialVersionUID = 724410007;

    /**
     * Setter for <code>tat0004_mod_login.auth_credentials._id</code>.
     */
    public void set_Id(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>tat0004_mod_login.auth_credentials._id</code>.
     */
    public UUID get_Id() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>tat0004_mod_login.auth_credentials.jsonb</code>.
     */
    public void setJsonb(JsonNode value) {
        set(1, value);
    }

    /**
     * Getter for <code>tat0004_mod_login.auth_credentials.jsonb</code>.
     */
    public JsonNode getJsonb() {
        return (JsonNode) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UUID, JsonNode> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UUID, JsonNode> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return AuthCredentials.AUTH_CREDENTIALS._ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<JsonNode> field2() {
        return AuthCredentials.AUTH_CREDENTIALS.JSONB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return get_Id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonNode component2() {
        return getJsonb();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return get_Id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonNode value2() {
        return getJsonb();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthCredentialsRecord value1(UUID value) {
        set_Id(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthCredentialsRecord value2(JsonNode value) {
        setJsonb(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthCredentialsRecord values(UUID value1, JsonNode value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthCredentialsRecord
     */
    public AuthCredentialsRecord() {
        super(AuthCredentials.AUTH_CREDENTIALS);
    }

    /**
     * Create a detached, initialised AuthCredentialsRecord
     */
    public AuthCredentialsRecord(UUID _Id, JsonNode jsonb) {
        super(AuthCredentials.AUTH_CREDENTIALS);

        set(0, _Id);
        set(1, jsonb);
    }
}
