/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.records;


import com.fasterxml.jackson.databind.JsonNode;
import com.generator.tables.TLogOperation;

import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLogOperationRecord extends UpdatableRecordImpl<TLogOperationRecord> implements Record10<UUID, String, String, String, String, String, LocalDateTime, String, String, JsonNode> {

    private static final long serialVersionUID = 265668651;

    /**
     * Setter for <code>userlib.t_log_operation.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>userlib.t_log_operation.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>userlib.t_log_operation.app_code</code>.
     */
    public void setAppCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>userlib.t_log_operation.app_code</code>.
     */
    public String getAppCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>userlib.t_log_operation.app_name</code>.
     */
    public void setAppName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>userlib.t_log_operation.app_name</code>.
     */
    public String getAppName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>userlib.t_log_operation.module_id</code>.
     */
    public void setModuleId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>userlib.t_log_operation.module_id</code>.
     */
    public String getModuleId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>userlib.t_log_operation.user_code</code>.
     */
    public void setUserCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>userlib.t_log_operation.user_code</code>.
     */
    public String getUserCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>userlib.t_log_operation.user_name</code>.
     */
    public void setUserName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>userlib.t_log_operation.user_name</code>.
     */
    public String getUserName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>userlib.t_log_operation.opt_time</code>.
     */
    public void setOptTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>userlib.t_log_operation.opt_time</code>.
     */
    public LocalDateTime getOptTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>userlib.t_log_operation.quote_addr</code>.
     */
    public void setQuoteAddr(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>userlib.t_log_operation.quote_addr</code>.
     */
    public String getQuoteAddr() {
        return (String) get(7);
    }

    /**
     * Setter for <code>userlib.t_log_operation.opt_mark</code>.
     */
    public void setOptMark(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>userlib.t_log_operation.opt_mark</code>.
     */
    public String getOptMark() {
        return (String) get(8);
    }

    /**
     * Setter for <code>userlib.t_log_operation.jsonb</code>.
     */
    public void setJsonb(JsonNode value) {
        set(9, value);
    }

    /**
     * Getter for <code>userlib.t_log_operation.jsonb</code>.
     */
    public JsonNode getJsonb() {
        return (JsonNode) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<UUID, String, String, String, String, String, LocalDateTime, String, String, JsonNode> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<UUID, String, String, String, String, String, LocalDateTime, String, String, JsonNode> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return TLogOperation.T_LOG_OPERATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TLogOperation.T_LOG_OPERATION.APP_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TLogOperation.T_LOG_OPERATION.APP_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TLogOperation.T_LOG_OPERATION.MODULE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TLogOperation.T_LOG_OPERATION.USER_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TLogOperation.T_LOG_OPERATION.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return TLogOperation.T_LOG_OPERATION.OPT_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TLogOperation.T_LOG_OPERATION.QUOTE_ADDR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TLogOperation.T_LOG_OPERATION.OPT_MARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<JsonNode> field10() {
        return TLogOperation.T_LOG_OPERATION.JSONB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAppCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAppName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getModuleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUserCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getOptTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getQuoteAddr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getOptMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonNode component10() {
        return getJsonb();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAppCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAppName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getModuleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUserCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getOptTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getQuoteAddr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getOptMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonNode value10() {
        return getJsonb();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLogOperationRecord value1(UUID value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLogOperationRecord value2(String value) {
        setAppCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLogOperationRecord value3(String value) {
        setAppName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLogOperationRecord value4(String value) {
        setModuleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLogOperationRecord value5(String value) {
        setUserCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLogOperationRecord value6(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLogOperationRecord value7(LocalDateTime value) {
        setOptTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLogOperationRecord value8(String value) {
        setQuoteAddr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLogOperationRecord value9(String value) {
        setOptMark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLogOperationRecord value10(JsonNode value) {
        setJsonb(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TLogOperationRecord values(UUID value1, String value2, String value3, String value4, String value5, String value6, LocalDateTime value7, String value8, String value9, JsonNode value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TLogOperationRecord
     */
    public TLogOperationRecord() {
        super(TLogOperation.T_LOG_OPERATION);
    }

    /**
     * Create a detached, initialised TLogOperationRecord
     */
    public TLogOperationRecord(UUID id, String appCode, String appName, String moduleId, String userCode, String userName, LocalDateTime optTime, String quoteAddr, String optMark, JsonNode jsonb) {
        super(TLogOperation.T_LOG_OPERATION);

        set(0, id);
        set(1, appCode);
        set(2, appName);
        set(3, moduleId);
        set(4, userCode);
        set(5, userName);
        set(6, optTime);
        set(7, quoteAddr);
        set(8, optMark);
        set(9, jsonb);
    }
}
