/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.records;


import com.fasterxml.jackson.databind.JsonNode;
import com.generator.tables.TMyLogin;

import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TMyLoginRecord extends UpdatableRecordImpl<TMyLoginRecord> implements Record7<UUID, String, String, String, LocalDateTime, String, JsonNode> {

    private static final long serialVersionUID = 311968831;

    /**
     * Setter for <code>tat0003_mod_login.t_my_login.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_my_login.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_my_login.user_code</code>.
     */
    public void setUserCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_my_login.user_code</code>.
     */
    public String getUserCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_my_login.user_name</code>.
     */
    public void setUserName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_my_login.user_name</code>.
     */
    public String getUserName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_my_login.login_type</code>.
     */
    public void setLoginType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_my_login.login_type</code>.
     */
    public String getLoginType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_my_login.login_time</code>.
     */
    public void setLoginTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_my_login.login_time</code>.
     */
    public LocalDateTime getLoginTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_my_login.login_ip</code>.
     */
    public void setLoginIp(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_my_login.login_ip</code>.
     */
    public String getLoginIp() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_my_login.jsonb</code>.
     */
    public void setJsonb(JsonNode value) {
        set(6, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_my_login.jsonb</code>.
     */
    public JsonNode getJsonb() {
        return (JsonNode) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UUID, String, String, String, LocalDateTime, String, JsonNode> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UUID, String, String, String, LocalDateTime, String, JsonNode> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return TMyLogin.T_MY_LOGIN.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TMyLogin.T_MY_LOGIN.USER_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TMyLogin.T_MY_LOGIN.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TMyLogin.T_MY_LOGIN.LOGIN_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return TMyLogin.T_MY_LOGIN.LOGIN_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TMyLogin.T_MY_LOGIN.LOGIN_IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<JsonNode> field7() {
        return TMyLogin.T_MY_LOGIN.JSONB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLoginType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component5() {
        return getLoginTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLoginIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonNode component7() {
        return getJsonb();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLoginType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getLoginTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLoginIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonNode value7() {
        return getJsonb();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMyLoginRecord value1(UUID value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMyLoginRecord value2(String value) {
        setUserCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMyLoginRecord value3(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMyLoginRecord value4(String value) {
        setLoginType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMyLoginRecord value5(LocalDateTime value) {
        setLoginTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMyLoginRecord value6(String value) {
        setLoginIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMyLoginRecord value7(JsonNode value) {
        setJsonb(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMyLoginRecord values(UUID value1, String value2, String value3, String value4, LocalDateTime value5, String value6, JsonNode value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TMyLoginRecord
     */
    public TMyLoginRecord() {
        super(TMyLogin.T_MY_LOGIN);
    }

    /**
     * Create a detached, initialised TMyLoginRecord
     */
    public TMyLoginRecord(UUID id, String userCode, String userName, String loginType, LocalDateTime loginTime, String loginIp, JsonNode jsonb) {
        super(TMyLogin.T_MY_LOGIN);

        set(0, id);
        set(1, userCode);
        set(2, userName);
        set(3, loginType);
        set(4, loginTime);
        set(5, loginIp);
        set(6, jsonb);
    }
}
