/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.records;


import com.fasterxml.jackson.databind.JsonNode;
import com.generator.tables.TWeXinUserinfo;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TWeXinUserinfoRecord extends UpdatableRecordImpl<TWeXinUserinfoRecord> implements Record10<UUID, String, String, Integer, String, String, String, String, String, JsonNode> {

    private static final long serialVersionUID = 2133416731;

    /**
     * Setter for <code>tat0003_mod_login.t_we_xin_userinfo.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_we_xin_userinfo.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_we_xin_userinfo.open_id</code>.
     */
    public void setOpenId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_we_xin_userinfo.open_id</code>.
     */
    public String getOpenId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_we_xin_userinfo.nick_name</code>.
     */
    public void setNickName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_we_xin_userinfo.nick_name</code>.
     */
    public String getNickName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_we_xin_userinfo.gender</code>.
     */
    public void setGender(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_we_xin_userinfo.gender</code>.
     */
    public Integer getGender() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_we_xin_userinfo.language</code>.
     */
    public void setLanguage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_we_xin_userinfo.language</code>.
     */
    public String getLanguage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_we_xin_userinfo.city</code>.
     */
    public void setCity(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_we_xin_userinfo.city</code>.
     */
    public String getCity() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_we_xin_userinfo.province</code>.
     */
    public void setProvince(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_we_xin_userinfo.province</code>.
     */
    public String getProvince() {
        return (String) get(6);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_we_xin_userinfo.country</code>.
     */
    public void setCountry(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_we_xin_userinfo.country</code>.
     */
    public String getCountry() {
        return (String) get(7);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_we_xin_userinfo.avatar_url</code>.
     */
    public void setAvatarUrl(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_we_xin_userinfo.avatar_url</code>.
     */
    public String getAvatarUrl() {
        return (String) get(8);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_we_xin_userinfo.watermark</code>.
     */
    public void setWatermark(JsonNode value) {
        set(9, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_we_xin_userinfo.watermark</code>.
     */
    public JsonNode getWatermark() {
        return (JsonNode) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<UUID, String, String, Integer, String, String, String, String, String, JsonNode> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<UUID, String, String, Integer, String, String, String, String, String, JsonNode> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return TWeXinUserinfo.T_WE_XIN_USERINFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TWeXinUserinfo.T_WE_XIN_USERINFO.OPEN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TWeXinUserinfo.T_WE_XIN_USERINFO.NICK_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TWeXinUserinfo.T_WE_XIN_USERINFO.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TWeXinUserinfo.T_WE_XIN_USERINFO.LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TWeXinUserinfo.T_WE_XIN_USERINFO.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TWeXinUserinfo.T_WE_XIN_USERINFO.PROVINCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TWeXinUserinfo.T_WE_XIN_USERINFO.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TWeXinUserinfo.T_WE_XIN_USERINFO.AVATAR_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<JsonNode> field10() {
        return TWeXinUserinfo.T_WE_XIN_USERINFO.WATERMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getOpenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNickName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getAvatarUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonNode component10() {
        return getWatermark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOpenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNickName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getAvatarUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonNode value10() {
        return getWatermark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinUserinfoRecord value1(UUID value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinUserinfoRecord value2(String value) {
        setOpenId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinUserinfoRecord value3(String value) {
        setNickName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinUserinfoRecord value4(Integer value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinUserinfoRecord value5(String value) {
        setLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinUserinfoRecord value6(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinUserinfoRecord value7(String value) {
        setProvince(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinUserinfoRecord value8(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinUserinfoRecord value9(String value) {
        setAvatarUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinUserinfoRecord value10(JsonNode value) {
        setWatermark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinUserinfoRecord values(UUID value1, String value2, String value3, Integer value4, String value5, String value6, String value7, String value8, String value9, JsonNode value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TWeXinUserinfoRecord
     */
    public TWeXinUserinfoRecord() {
        super(TWeXinUserinfo.T_WE_XIN_USERINFO);
    }

    /**
     * Create a detached, initialised TWeXinUserinfoRecord
     */
    public TWeXinUserinfoRecord(UUID id, String openId, String nickName, Integer gender, String language, String city, String province, String country, String avatarUrl, JsonNode watermark) {
        super(TWeXinUserinfo.T_WE_XIN_USERINFO);

        set(0, id);
        set(1, openId);
        set(2, nickName);
        set(3, gender);
        set(4, language);
        set(5, city);
        set(6, province);
        set(7, country);
        set(8, avatarUrl);
        set(9, watermark);
    }
}
