/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.records;


import com.fasterxml.jackson.databind.JsonNode;
import com.generator.tables.TWeXinOkapi;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TWeXinOkapiRecord extends UpdatableRecordImpl<TWeXinOkapiRecord> implements Record8<UUID, String, String, String, String, String, String, JsonNode> {

    private static final long serialVersionUID = 1849186841;

    /**
     * Setter for <code>tat0003_mod_login.t_we_xin_okapi.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_we_xin_okapi.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_we_xin_okapi.tanent_id</code>.
     */
    public void setTanentId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_we_xin_okapi.tanent_id</code>.
     */
    public String getTanentId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_we_xin_okapi.app_id</code>.
     */
    public void setAppId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_we_xin_okapi.app_id</code>.
     */
    public String getAppId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_we_xin_okapi.app_secret</code>.
     */
    public void setAppSecret(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_we_xin_okapi.app_secret</code>.
     */
    public String getAppSecret() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_we_xin_okapi.user_name</code>.
     */
    public void setUserName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_we_xin_okapi.user_name</code>.
     */
    public String getUserName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_we_xin_okapi.password</code>.
     */
    public void setPassword(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_we_xin_okapi.password</code>.
     */
    public String getPassword() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_we_xin_okapi.note</code>.
     */
    public void setNote(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_we_xin_okapi.note</code>.
     */
    public String getNote() {
        return (String) get(6);
    }

    /**
     * Setter for <code>tat0003_mod_login.t_we_xin_okapi.jsonb</code>.
     */
    public void setJsonb(JsonNode value) {
        set(7, value);
    }

    /**
     * Getter for <code>tat0003_mod_login.t_we_xin_okapi.jsonb</code>.
     */
    public JsonNode getJsonb() {
        return (JsonNode) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<UUID, String, String, String, String, String, String, JsonNode> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<UUID, String, String, String, String, String, String, JsonNode> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return TWeXinOkapi.T_WE_XIN_OKAPI.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TWeXinOkapi.T_WE_XIN_OKAPI.TANENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TWeXinOkapi.T_WE_XIN_OKAPI.APP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TWeXinOkapi.T_WE_XIN_OKAPI.APP_SECRET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TWeXinOkapi.T_WE_XIN_OKAPI.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TWeXinOkapi.T_WE_XIN_OKAPI.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TWeXinOkapi.T_WE_XIN_OKAPI.NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<JsonNode> field8() {
        return TWeXinOkapi.T_WE_XIN_OKAPI.JSONB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTanentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAppSecret();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonNode component8() {
        return getJsonb();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTanentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAppSecret();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonNode value8() {
        return getJsonb();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinOkapiRecord value1(UUID value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinOkapiRecord value2(String value) {
        setTanentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinOkapiRecord value3(String value) {
        setAppId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinOkapiRecord value4(String value) {
        setAppSecret(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinOkapiRecord value5(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinOkapiRecord value6(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinOkapiRecord value7(String value) {
        setNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinOkapiRecord value8(JsonNode value) {
        setJsonb(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWeXinOkapiRecord values(UUID value1, String value2, String value3, String value4, String value5, String value6, String value7, JsonNode value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TWeXinOkapiRecord
     */
    public TWeXinOkapiRecord() {
        super(TWeXinOkapi.T_WE_XIN_OKAPI);
    }

    /**
     * Create a detached, initialised TWeXinOkapiRecord
     */
    public TWeXinOkapiRecord(UUID id, String tanentId, String appId, String appSecret, String userName, String password, String note, JsonNode jsonb) {
        super(TWeXinOkapi.T_WE_XIN_OKAPI);

        set(0, id);
        set(1, tanentId);
        set(2, appId);
        set(3, appSecret);
        set(4, userName);
        set(5, password);
        set(6, note);
        set(7, jsonb);
    }
}
