/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.daos;


import com.fasterxml.jackson.databind.JsonNode;
import com.generator.tables.TLogLogin;
import com.generator.tables.records.TLogLoginRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLogLoginDao extends DAOImpl<TLogLoginRecord, com.generator.tables.pojos.TLogLogin, UUID> {

    /**
     * Create a new TLogLoginDao without any configuration
     */
    public TLogLoginDao() {
        super(TLogLogin.T_LOG_LOGIN, com.generator.tables.pojos.TLogLogin.class);
    }

    /**
     * Create a new TLogLoginDao with an attached configuration
     */
    public TLogLoginDao(Configuration configuration) {
        super(TLogLogin.T_LOG_LOGIN, com.generator.tables.pojos.TLogLogin.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UUID getId(com.generator.tables.pojos.TLogLogin object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.generator.tables.pojos.TLogLogin> fetchById(UUID... values) {
        return fetch(TLogLogin.T_LOG_LOGIN.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.generator.tables.pojos.TLogLogin fetchOneById(UUID value) {
        return fetchOne(TLogLogin.T_LOG_LOGIN.ID, value);
    }

    /**
     * Fetch records that have <code>user_code IN (values)</code>
     */
    public List<com.generator.tables.pojos.TLogLogin> fetchByUserCode(String... values) {
        return fetch(TLogLogin.T_LOG_LOGIN.USER_CODE, values);
    }

    /**
     * Fetch records that have <code>user_name IN (values)</code>
     */
    public List<com.generator.tables.pojos.TLogLogin> fetchByUserName(String... values) {
        return fetch(TLogLogin.T_LOG_LOGIN.USER_NAME, values);
    }

    /**
     * Fetch records that have <code>login_type IN (values)</code>
     */
    public List<com.generator.tables.pojos.TLogLogin> fetchByLoginType(Short... values) {
        return fetch(TLogLogin.T_LOG_LOGIN.LOGIN_TYPE, values);
    }

    /**
     * Fetch records that have <code>login_time IN (values)</code>
     */
    public List<com.generator.tables.pojos.TLogLogin> fetchByLoginTime(LocalDateTime... values) {
        return fetch(TLogLogin.T_LOG_LOGIN.LOGIN_TIME, values);
    }

    /**
     * Fetch records that have <code>login_ip IN (values)</code>
     */
    public List<com.generator.tables.pojos.TLogLogin> fetchByLoginIp(String... values) {
        return fetch(TLogLogin.T_LOG_LOGIN.LOGIN_IP, values);
    }

    /**
     * Fetch records that have <code>jsonb IN (values)</code>
     */
    public List<com.generator.tables.pojos.TLogLogin> fetchByJsonb(JsonNode... values) {
        return fetch(TLogLogin.T_LOG_LOGIN.JSONB, values);
    }
}
