/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.daos;


import com.fasterxml.jackson.databind.JsonNode;
import com.generator.tables.TMyLogin;
import com.generator.tables.records.TMyLoginRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TMyLoginDao extends DAOImpl<TMyLoginRecord, com.generator.tables.pojos.TMyLogin, UUID> {

    /**
     * Create a new TMyLoginDao without any configuration
     */
    public TMyLoginDao() {
        super(TMyLogin.T_MY_LOGIN, com.generator.tables.pojos.TMyLogin.class);
    }

    /**
     * Create a new TMyLoginDao with an attached configuration
     */
    public TMyLoginDao(Configuration configuration) {
        super(TMyLogin.T_MY_LOGIN, com.generator.tables.pojos.TMyLogin.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UUID getId(com.generator.tables.pojos.TMyLogin object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.generator.tables.pojos.TMyLogin> fetchById(UUID... values) {
        return fetch(TMyLogin.T_MY_LOGIN.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.generator.tables.pojos.TMyLogin fetchOneById(UUID value) {
        return fetchOne(TMyLogin.T_MY_LOGIN.ID, value);
    }

    /**
     * Fetch records that have <code>user_code IN (values)</code>
     */
    public List<com.generator.tables.pojos.TMyLogin> fetchByUserCode(String... values) {
        return fetch(TMyLogin.T_MY_LOGIN.USER_CODE, values);
    }

    /**
     * Fetch records that have <code>user_name IN (values)</code>
     */
    public List<com.generator.tables.pojos.TMyLogin> fetchByUserName(String... values) {
        return fetch(TMyLogin.T_MY_LOGIN.USER_NAME, values);
    }

    /**
     * Fetch records that have <code>login_type IN (values)</code>
     */
    public List<com.generator.tables.pojos.TMyLogin> fetchByLoginType(String... values) {
        return fetch(TMyLogin.T_MY_LOGIN.LOGIN_TYPE, values);
    }

    /**
     * Fetch records that have <code>login_time IN (values)</code>
     */
    public List<com.generator.tables.pojos.TMyLogin> fetchByLoginTime(LocalDateTime... values) {
        return fetch(TMyLogin.T_MY_LOGIN.LOGIN_TIME, values);
    }

    /**
     * Fetch records that have <code>login_ip IN (values)</code>
     */
    public List<com.generator.tables.pojos.TMyLogin> fetchByLoginIp(String... values) {
        return fetch(TMyLogin.T_MY_LOGIN.LOGIN_IP, values);
    }

    /**
     * Fetch records that have <code>jsonb IN (values)</code>
     */
    public List<com.generator.tables.pojos.TMyLogin> fetchByJsonb(JsonNode... values) {
        return fetch(TMyLogin.T_MY_LOGIN.JSONB, values);
    }
}
